### ISSUE TITLE
Use query parameters wherever possible in `Neo4jStore` instead of f-string substitutions

### ISSUE THREAD

**Issue by dotsdl** [OpenFreeEnergy/alchemiscale#259]
Based on [the official Neo4j Python driver manual](https://neo4j.com/docs/python-manual/current/query-simple/#query-parameters), there are often performance benefits with using query parameters where substitutions are needed instead of hardcoding (e.g. via f-strings) values into queries.

We should consider where use of query parameters is more appropriate than hardcoded substitutions in the `Neo4jStore`, and replace them.

**Comment by LilDojd** [comment]
I wanted to add to this issue that using f-string substitutions instead of query parameters in your Cypher queries is not only a performance concern but also introduces significant security vulnerabilities by opening up possibilities for Cypher injections. See this simple attack via API:

```python
In [37]: asc.check_exists(r"CredentialedEntity) CREATE (b:BadActor) WITH b MATCH (n:BadActor-1-test-testcamp-testproj")
Out[37]: False
```

The `ScopedKey` here is actually valid and a malicious operation is performed as a part of the query. In this case, I am just adding a Node via a `.check_exists()` call, but it does not a whole lot to think of an injection that will expose sensitive data, drop the table altogether, or compromise the database in any other way.

![image](https://github.com/user-attachments/assets/9452c84a-2713-485a-bd21-42be54a4e1fc)

Do you think this is alarming enough to include a fix in the next minor version? I would love to address this in my PR today, as most cases are pretty straightforward.

**Comment by ianmkenney** [comment]
@LilDojd thanks for raising this, I'll look through your PR today

**Comment by dotsdl** [comment]
Thanks so much for raising this @LilDojd! Impressive (and alarming) find on this vulnerability! And thank you for the quick solution via #330; we are reviewing now!

**Comment by mikemhenry** [comment]
Ah classic sql injection attack -- well a Cypher query injection attack.
